### ISSUE TITLE
Plugin error and reload

### ISSUE THREAD

**Issue by sera4000** [janmg/logstash-input-azure_blob_storage#11] opened 2020-12-17 09:14 UTC
Hi Jan,

I'm getting an error (and plugin restarting) for one container only. It happens often but not every time. Other containers are working fine with very similar plugin config (in other Logstash pipelines). The container is currently 60GB with 1000 blobs and gets written to continuously. In the error log I'm seeing:

Error: Connection reset by peer
  Exception: Faraday::ConnectionFailed
  Stack: org/jruby/ext/openssl/SSLSocket.java:874:in `sysread_nonblock'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/jruby-openssl-0.10.5-java/lib/jopenssl23/openssl/buffering.rb:182:in `read_nonblock'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb:175:in `rbuf_fill'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb:125:in `read'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:293:in `block in read_body_0'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:278:in `inflater'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:283:in `read_body_0'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:204:in `read_body'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1224:in `block in get'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.587/lib/seahorse/client/net_http/patches.rb:38:in `block in new_transport_request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:165:in `reading_body'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-core-2.11.587/lib/seahorse/client/net_http/patches.rb:37:in `new_transport_request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1474:in `request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1467:in `block in request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:914:in `start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1465:in `request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1223:in `get'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:85:in `perform_request'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/http_response_helper.rb:27:in `set_up_response'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/http/http_request.rb:149:in `call'
org/jruby/RubyMethod.java:115:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/http/signer_filter.rb:28:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/service.rb:36:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/filtered_service.rb:34:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/signed_service.rb:41:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-common-1.1.0/lib/azure/storage/common/service/storage_service.rb:60:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-blob-1.1.0/lib/azure/storage/blob/blob_service.rb:179:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-blob-1.1.0/lib/azure/storage/blob/blob.rb:106:in `get_blob'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_blob_storage-0.11.4/lib/logstash/inputs/azure_blob_storage.rb:306:in `full_read'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_blob_storage-0.11.4/lib/logstash/inputs/azure_blob_storage.rb:238:in `block in run'
org/jruby/RubyHash.java:1415:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_blob_storage-0.11.4/lib/logstash/inputs/azure_blob_storage.rb:233:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:378:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:369:in `block in start_input'

Is there a way for me to debug this? I'm using the latest plugin version.

Thanks,
Sera

**Comment by sera4000** [comment] 2020-12-17 09:19
Logstash config looks like this:

input {
    azure_blob_storage {
        storageaccount => "mystorageaccount"
        access_key => "${MYKEY}"
        container => "mycontainer"
        codec => "json_lines"
        registry_create_policy => "start_fresh"
        interval => 300
        debug_timer => true
        registry_local_path => '/usr/share/logstash/plugins/5'
        type => "mylogtype"
    }
}

**Comment by sera4000** [comment] 2020-12-17 09:51
Additional info:

When the failure does not occur for a while, and I then change from 'start_fresh' to 'resume' mode, I get the same errors as above but also get this continuously:

caught: marshal data too short
loading registry failed for attempt 1 of 3

**Comment by janmg** [comment] 2020-12-17 13:05
The plugin lists all the files in the container and compares it to the registry to create a worklist. If that worklist contains a file that hasn't been read before it uses full_read to fetch that blob and store the size of what has been read. So if the blob grows after reading, the added data can be read in the next round.

There is not many safety mechanisms built in to check if the actual files still exist and if they are not actually empty. The plugin will crash and restart.

After a couple of months where I did not have much time to look into this plugin, I finally have recreated my dev/test environment and started looking into ways to catch errors and not crash the plugin but work around connection failures and parse errors. Your report will help me find some of these cases, but it would help if you can identify the file that caused the issue.

**Comment by janmg** [comment] 2020-12-17 13:06
marshal data too short probably means the file is empty. If I can't solve it, I'll release a version with better debugging around the json marshalling

**Comment by sera4000** [comment] 2020-12-17 15:19
Thanks. Not sure how to approach this, but happy to help troubleshoot. I have no idea how I would identify the file as there are many. When I leave it in 'start fresh' mode, I am getting the "plugin had an unrecoverable error" message almost all the time, and some data gets ingested into Logstash although I think some is missing. When I change to 'resume' mode, I get the 'marshal data too short' error.

**Comment by janmg** [comment] 2020-12-19 13:54
I pushed 0.11.5 just now and I added a begin rescue loop with a log statement, so it will skip files that can't be read instead of crashing the whole plugin. If we need to dig deeper, the log entry should print the filename so you can look at it with the storageexplorer from microsoft.

**Comment by sera4000** [comment] 2020-12-20 06:24
I have updated to ver 0.11.5, and so far have seen the following errors when running in 'resume' mode:


[2020-12-20T05:53:20,970][ERROR][logstash.inputs.azureblobstorage][frontdoorlogs][95c353b2fae9e51b984eb662a4c5cee7369d8446c486285fb244196c7da405f] Failed to read resourceId=/SUBSCRIPTIONS/E9CC885A-1D03-8752-C752-7A6B49A33653/RESOURCEGROUPS/FRONTDOOR/PROVIDERS/MICROSOFT.NETWORK/FRONTDOORS/FRONTDOOR-INFO/y=2020/m=12/d=20/h=05/m=00/PT1H.json because of: Connection reset by peer .. will continue and pretend this never happened
[2020-12-20T05:53:20,974][ERROR][logstash.inputs.azureblobstorage][frontdoorlogs][95c353b2fae9e51b984eb662a4c5cee7369d8446c486285fb244196c7da405f] codec exception: class org.jruby.RubyNil cannot be cast to class org.jruby.RubyString (org.jruby.RubyNil and org.jruby.RubyString are in unnamed module of loader 'app') .. will continue and pretend this never happened


I received these errors twice (on the first 2 cycles), and after that I am not seeing the errors again. The data being ingested in elasticsearch looks ok - not sure if anything is missing but the flow seems continuous.


Thanks,
Sera

**Comment by janmg** [comment] 2020-12-20 08:13
'pretend this never happened' is the log message that will print with the file and exception message. So when the plugin tells the blob_client from Microsoft to fetch the contents of a file it fails. My plugin now doesn't crash on the file and continues. But the files that couldn't be processed will remain there, so if they grow they will be retried. I assume the file is empty and reading an empty file is not valid json. Can you check with the storage explorer (the desktop application or the portal page) what the file looks like?

**Comment by sera4000** [comment] 2020-12-21 05:52
The file causing the problem is an 'append blob'. A new file is created each hour and is appended continuously during the hour. At the beginning of each hour the plugin works fine, and it's only after about 45 minutes into the hour that the problem happens. It happens every hour after 40 - 50 minutes.

Do you think the issue might be caused by something related to:

https://github.com/Azure/azure-storage-js/issues/51

https://stackoverflow.com/questions/52545226/downloading-azure-append-blob-during-upload-results-in-error-412

Is it possible for the plugin to do a 'snapshot' instead of a download? Or something along those lines?

**Comment by janmg** [comment] 2020-12-21 11:22
"Connection reset by peer" may be caused by the errors you suggested, unfortunately logstash depends on faraday as well and because it needs a specific version I can't update the azure-blob version. I think the append blob should have still worked and the file should be read incrementally every interval. if files changes because the size grows my plugin should add the delta on the work list and since you use json_lines I think each line can be processed individually.

I'll create a simple standalone ruby file for debugging purposes so you can run them on the files that are reported to be broken. It may be a timeout issue, it maybe a json parse error. I'll create the debug json file when I have a spare moment. It will be something based on the quickstart, that's how I learned how block blob work and how files grow over time.

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-ruby
https://github.com/Azure-Samples/storage-blobs-ruby-quickstart.git

**Comment by sera4000** [comment] 2020-12-21 15:42
I just took a good look through the logs being sent to elasticsearch. I have set the plugin to run every 10 minutes. I didn't notice this before, but duplicate entries are being ingested into elasticsearch. It seems that each log entry is repeated 4 or 5 times in elasticsearch. So it appears that the entire blob file contents are ingested each cycle and then sent to elasticsearch, so when the blob file grows all of the existing data is uploaded again each cycle. Do you think this plugin will allow me to avoid duplication of log entries?

**Comment by sera4000** [comment] 2020-12-22 06:04
I have a fresh append blob created each hour, which grows continually during the hour. After each hour a new append blob is created (in a new folder) and then that new blob file grows continually for an hour. So I am actually seeing two different problems. Firstly, the plugin is getting "Connection reset by peer" after about 40 minutes into each hour. Secondly, each json line log entry from the file is getting ingested every interval, causing duplication of json lines in elasticsearch. I hadn't noticed this duplication before on my other containers, as the interval is set to 6 hours - but the exact same thing is happening.

One workaround fix for all of this might be a setting to tell the plugin to ingest only files older than 'x' minutes. If that was possible, and I set it to ingest only files older than 120 minutes, I think the issue would not occur.

Sorry to throw more problems at you. Let me know what you think and how I can help.

**Comment by janmg** [comment] 2020-12-22 13:59
I really don't mind fixing issues, it just takes time and my job takes precedence. Since I changed jobs I needed a lot of time to rebuild my environments and now I will commit a test file to see what's happening. I originally learned how blob.blocks worked by using examples from storage-blob-ruby-getting-started and now I rebuild the test I also checked what happens with append blobs. blobs can grow by adding blocks, but the appendblobs don't expose the name or size of the blobs, so the delta doesn't work.

I will rethink the strategy for appendblobs. Any change to released code has an unpredictable knock on effect. I created the plugin originally for nsgflowlogs and other mechanisms like json_files and append blocks, work in surprising ways.

**Comment by janmg** [comment] 2021-02-09 17:46
I'll create 0.11.6 tomorrow, since I merged the pull request from yann-oaf. He found that the learning doesn't use maxresults to limit the files, but is actually max_results. In the API it is maxresults, but since I use the https://github.com/Azure/azure-storage-ruby library the option contains the underscore. Fingers crossed it solves your issue =)

**Comment by janmg** [comment] 2021-02-11 17:52
I pushed 0.11.6 ... I think your problem is related to empty files, so I write some loops to avoid processing empty files. If this does not help I would need a lot of debug logs.

**Comment by janmg** [comment] 2022-01-17 14:04
This is most likely fixed with skipping files that the plugin can't read

**Closed as completed by janmg** 2022-01-17 14:04 UTC
